//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blog.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public int Id { get; set; }
        public string DOP { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Author { get; set; }
        public Nullable<int> Likes { get; set; }
        public Nullable<int> Report { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> DummyInt { get; set; }
        public string DummyString { get; set; }
    
        public virtual User User { get; set; }
    }
}
